// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isValidHttpsUrl(value: string): boolean {
  try {
    const u = new URL(value);
    return u.protocol === 'https:' && u.hostname.length > 0;
  } catch {
    return false;
  }
}

function isPlausibleSupabaseKey(value: string): boolean {
  // Supabase publishable/anon keys are JWTs (3 dot-separated base64url segments)
  // or new-format keys prefixed with sb_*. Accept either.
  return /^sb_[A-Za-z0-9_]+$/.test(value) || /^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(value);
}

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  const errors: string[] = [];
  if (!SUPABASE_URL) errors.push('SUPABASE_URL ausente');
  else if (!isValidHttpsUrl(SUPABASE_URL)) errors.push('SUPABASE_URL inválida (esperado https://...)');

  if (!SUPABASE_PUBLISHABLE_KEY) errors.push('SUPABASE_PUBLISHABLE_KEY ausente');
  else if (!isPlausibleSupabaseKey(SUPABASE_PUBLISHABLE_KEY)) errors.push('SUPABASE_PUBLISHABLE_KEY com formato inválido');

  if (errors.length) {
    const message = `Configuração Supabase inválida: ${errors.join('; ')}.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

